name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    if: ${{ false }}
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pending changes
        uses: actions/checkout@v3
      - name: Setup QEMU for possible emulation
        uses: docker/setup-qemu-action@v1

      - name: Run Build
        uses: ./.github/actions/bazel-docker
        with:
          bazel: build //:protoc -c opt
          bazel-cache: cpp_bazel/Optimized
          credentials: ${{secrets.GAR_SERVICE_ACCOUNT}}

  bash:
    name: Bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pending changes
        uses: actions/checkout@v3
      - name: Setup QEMU for possible emulation
        uses: docker/setup-qemu-action@v1

      - name: Run Bash
        uses: ./.github/actions/bazel-docker
        with:
          bash: echo 'Hello - $BAZEL_FLAGS'
          bazel-cache: cpp_bazel/Optimized
          credentials: ${{secrets.GAR_SERVICE_ACCOUNT}}
